name: matrix demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
                include: # additional single combo, 18+ubuntu; If included above, it would have 2 combos, 18+Ubuntu, 18+windows
                    - node-version: 18
                      operating-system: ubuntu-latest
                exclude: #excludes this combo
                    - node-version: 12
                      operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: install Node JS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build